export default [
    {
      id: 1,
      postedOn: new Date(),
      title: "Marketing",
      type: "Full time",
      location: "In-office",
      companyName: "S.K Enterprises",
      companyUrl: "sk.com",
      skills: ["good communication", "well-mannered", "Confident"],
      link: "https://sk.com/careers",
    },
    {
      id: 2,
      postedOn: new Date(),
      title: "Team Leader",
      type: "Full time",
      location: "Office",
      companyName: "Yash Pvt.Ltd",
      companyUrl: "Yash.com",
      skills: [" strong organization", "Critical Thinking"],
      link: "https://yash.com/jobs",
    },
    {
      id: 3,
      postedOn: new Date(),
      title: "Travel Agent",
      type: "Contract",
      location: "Remote",
      companyName: "Venus World",
      companyUrl: "https://venus.com",
      skills: ["Enthusiastic", "Great communication"],
      link: "https://facebook.com/careers",
    },
  ];